### PR TITLE
Looks better.. by far.

### PR DESCRIPTION
**Pull request by jrodr10**

### CODE REVIEW

**Comment by xXNiceAssasinl0** [comment]
:/

**Comment by xXNiceAssasinl0** [comment]
Why you want change Readme?

**Comment by jrodr10** [comment]
Proper English bro.. thats all... i take it english isn't your first language

**Comment by xXNiceAssasinl0** [comment]
Nope.. english is not my first language.

**Comment by jrodr10** [comment]
I'm only trying to make it sound more proper.. i am not trying to be offensive.. bro

**Comment by xXNiceAssasinl0** [comment]
I want merge the pull.

**Comment by jrodr10** [comment]
Won't? @xXNiceAssasinl0  or Want to ?

**Comment by xXNiceAssasinl0** [comment]
Want to.

**Comment by jrodr10** [comment]
Alright, it's ready to be merged. :)

**Pull request merged**
